### ISSUE TITLE
netbox-dns: Replace auroraresearchlab/netbox-dns

### ISSUE THREAD

**Issue by YoSiJo** [netbox-community/awesome-netbox#3]
### Link to suggestion

https://github.com/netbox-community/awesome-netbox

### Describe your suggesiton

As seen in the discussion [here](https://github.com/auroraresearchlab/netbox-dns/discussions/299), the repo is probably dead.
The most obvious replacement will probably be the repo https://github.com/peteeckel/netbox-plugin-dns
But I wanted to put this first for discussion, before one makes unnecessary MR for it.
A few thumbs up, but would be enough and I look that I create the MR the days, or someone is just faster. ;)

**Comment by arthanson** [comment]
Updated in new release.
